### ISSUE TITLE
问下如何解决？

### ISSUE THREAD

**Issue by woaini521** [fzf404/Monit#55]
node:20256) UnhandledPromiseRejectionWarning: TypeError: Cannot read properties of undefined (reading 'get')
    at getAppLocale (D:\jingdian\vue3\Monit\dist\main\index.js:791:18)
    at initMenu (D:\jingdian\vue3\Monit\dist\main\index.js:1083:19)
    at initTray (D:\jingdian\vue3\Monit\dist\main\index.js:1197:3)
    at App.<anonymous> (D:\jingdian\vue3\Monit\dist\main\index.js:1268:3)
(Use `electron --trace-warnings ...` to show where the warning was created)
(node:20256) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)

**Comment by fzf404** [comment]
mian 分支的代码暂时没有 stable

**Comment by fzf404** [comment]
请参考 #56 获取最新进展！
